name: Continuous Delivery

on:
  push:
    branches:
      - main
      - develop
      - 'hotfix/**'
      - 'feature/**'
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' &&
      (startsWith(github.ref, 'refs/heads/main') ||
       startsWith(github.ref, 'refs/heads/develop') ||
       startsWith(github.ref, 'refs/heads/hotfix/') ||
       startsWith(github.ref, 'refs/heads/feature/'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install python-semantic-release
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Semantic Release (bump & tag)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release --verbose publish

  deploy:
    name: Build & Push Docker Image
    needs: release
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION_TAG}" >> $GITHUB_ENV
          echo "Extracted version: ${VERSION_TAG}"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:latest
